[package]
name = "seer_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
futures = "0.3"
reth = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", package = "reth-exex" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
alloy = "0.1.0"
revm = { version = "9.0.0", features = [
    "std",
    "secp256k1",
    "blst",
], default-features = false }
revm-primitives = { version = "4.0.0", features = [
    "std",
], default-features = false }
revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors", rev = "53aa2b2" }
trie-rs = "0.4.2"
libp2p = { version = "0.53.2", features = [
    "floodsub",
    "mdns",
    "macros",
    "dns",
    "tcp",
] }

alloy-primitives = "0.7.5"
dotenv = "0.15.0"
log = "0.4.21"
thiserror = "1.0.61"
swarm = "0.1.0"
libp2p-core = "0.41.2"
libp2p-swarm = "0.44.2"
libp2p-identity = "0.2.8"
libp2p-mdns = { version = "0.45.1", features = ["tokio"] }
reqwest = "0.12.4"

[patch.crates-io]
revm = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
revm-interpreter = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
revm-precompile = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }
revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "a28a543" }

# [lib]
# proc-macro = true
